[project]
name = "mani-ai-roadmap"
version = "0.1.0"
description = "This is a project to start my journey in Machine learning from 0 to 100 !"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "plotly>=6.9.0",
    "pyautogui>=0.9.54",
    "seaborn>=0.13.2",
]
